---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.23
        resources:
          limits:
            memory: "500Mi"
            cpu: "1"
        ports:
        - containerPort: 80
