---
apiVersion: v1
kind: Pod
metadata:
  name: sample-annotations
  annotations:
    annotation1: vall
    annotaiton2: "200"
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
