---
apiVersion: v1
kind: Pod
metadata:
  name: sample-label
  labels:
    label1: val1
    label2: val2
spec:
  containers:
  - name: nginx-container
    image: nginx:1.16
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
